### ISSUE TITLE
`run.py` doesn't work if you use the default `--algo` option

### ISSUE THREAD

**Issue by Iain-S** [DeepIntoStreams/Evaluation-of-Time-Series-Generative-Models#3]
The default `--algo` value is `"LSTM_DEV"` but that doesn't seem to correspond to anything in the `trainer` dict in `models.py`.

Running `python run.py`, without arguments errors with 

```python
Traceback (most recent call last):
  File "run.py", line 182, in <module>
    main(config)
  File "run.py", line 57, in main
    trainer = get_trainer(config, train_dl, test_dl)
  File "/usr/src/app/src/baselines/models.py", line 64, in get_trainer
    trainer = {
KeyError: 'AR1_LSTM_DEV'
```

**Comment by HangLou** [comment]
Thank you for spotting the bug. I will close this issue with a fix through PR #6.
